import { z } from 'zod/v4';

export const ExtractedInsuranceDataSchema = z.object({
  insuranceCompanyName: z.string(),
  policyNumber: z.string(),
  contractHolder: z.string(),
  insuredPerson: z.string(),
  beneficiary: z.string().nullable(),
  insuranceType: z.string(),
  isLifeInsurance: z.boolean(),
  isAnnuity: z.boolean(),
  deathBenefitAmount: z.number().nullable(),
  maturityBenefitAmount: z.number().nullable(),
  annualAnnuityAmount: z.number().nullable(),
  annuityPaymentPeriodYears: z.number().nullable(),
  annuityStartDate: z.string().nullable(),
  hasAnnuityPaymentStarted: z.boolean().nullable(),
  guaranteePeriodYears: z.number().nullable(),
  contractDate: z.string(),
  maturityDate: z.string().nullable(),
  totalPremiumsPaid: z.number().nullable(),
  surrenderValue: z.number().nullable(),
  lumpSumOptionAmount: z.number().nullable(),
  assumedInterestRate: z.number().nullable(),
  paidOutAmount: z.number().nullable(),
  paymentReason: z.string().nullable(),
  documentType: z.enum(['保険証券', '支払通知書', 'その他']),
  rawNotes: z.string().nullable(),
});
