import { NextResponse } from 'next/server'
import { createDeadline, listDeadlines } from '@/lib/groupware/store'
import type { Deadline } from '@/lib/groupware/types'

export const runtime = 'nodejs'

export async function GET(req: Request) {
  const url = new URL(req.url)
  const clientId = url.searchParams.get('clientId') ?? undefined
  const deadlines = await listDeadlines(clientId)
  return NextResponse.json({ deadlines })
}

export async function POST(req: Request) {
  const body = (await req.json()) as Partial<Deadline>
  if (!body.clientId || !body.category || !body.kind || !body.dueDate || !body.status) {
    return NextResponse.json(
      { error: 'clientId, category, kind, dueDate, status are required' },
      { status: 400 },
    )
  }
  const created = await createDeadline({
    clientId: body.clientId,
    category: body.category,
    kind: body.kind,
    periodLabel: body.periodLabel,
    dueDate: body.dueDate,
    status: body.status,
    note: body.note,
    submittedAt: body.submittedAt,
    paidAt: body.paidAt,
    taxAmount: body.taxAmount,
    autoGenerated: body.autoGenerated ?? false,
  })
  return NextResponse.json({ deadline: created }, { status: 201 })
}
