/**
 * 決算月などの基本情報から、税務上の各種期限を自動算出するヘルパ。
 * 実運用では個別事情があるため、生成後に編集可能な下書きとして扱う。
 */
import type {
  Client,
  ConsumptionTaxFilingFrequency,
  CorporationProfile,
  Deadline,
} from './types'

export interface DeadlineDraft {
  clientId: string
  category: Deadline['category']
  kind: Deadline['kind']
  periodLabel: string
  dueDate: string
  status: Deadline['status']
  note?: string
  autoGenerated: true
}

/** 月末日を取得 */
function lastDayOfMonth(year: number, month1Based: number): number {
  return new Date(year, month1Based, 0).getDate()
}

function toISODate(year: number, month1Based: number, day: number): string {
  const mm = String(month1Based).padStart(2, '0')
  const dd = String(day).padStart(2, '0')
  return `${year}-${mm}-${dd}`
}

/** 月加算 (month1Basedに n を足す)。年をまたぐ場合は繰り上げ。 */
function addMonths(year: number, month1Based: number, n: number): { year: number; month: number } {
  const totalFromJan = (year * 12 + (month1Based - 1)) + n
  const y = Math.floor(totalFromJan / 12)
  const m = (totalFromJan % 12) + 1
  return { year: y, month: m }
}

/** 「当期」の決算日(ISO)を返す。基準日以降の最初の決算日を採用。 */
export function getFiscalYearEndDate(
  profile: CorporationProfile,
  baseDate: Date = new Date(),
): string | undefined {
  if (!profile.fiscalYearEndMonth) return undefined
  const month = profile.fiscalYearEndMonth
  const targetDay = profile.fiscalYearEndDay ?? 0 // 0は月末扱い
  const baseY = baseDate.getFullYear()
  const candidates = [baseY, baseY + 1]
  for (const y of candidates) {
    const day = targetDay > 0 ? targetDay : lastDayOfMonth(y, month)
    const iso = toISODate(y, month, day)
    if (iso >= baseDate.toISOString().slice(0, 10)) return iso
  }
  return undefined
}

/** 法人の確定申告期限: 決算日から2ヶ月後の応当日 */
function corporationFilingDueDate(fiscalYearEndISO: string): string {
  const [y, m, d] = fiscalYearEndISO.split('-').map(Number)
  const { year, month } = addMonths(y, m, 2)
  const day = Math.min(d, lastDayOfMonth(year, month))
  return toISODate(year, month, day)
}

/** 法人の中間申告期限: 事業年度開始から6ヶ月経過後の期間末日の2ヶ月後 */
function corporationInterimFilingDueDate(fiscalYearEndISO: string): string {
  const [y, m, d] = fiscalYearEndISO.split('-').map(Number)
  // 中間事業年度末 = 決算日の6ヶ月前
  const { year: midY, month: midM } = addMonths(y, m, -6)
  const midDay = Math.min(d, lastDayOfMonth(midY, midM))
  // その2ヶ月後
  const { year: dueY, month: dueM } = addMonths(midY, midM, 2)
  const dueDay = Math.min(midDay, lastDayOfMonth(dueY, dueM))
  return toISODate(dueY, dueM, dueDay)
}

/** 消費税中間申告の月数間隔 */
function consumptionInterimMonthsList(freq?: ConsumptionTaxFilingFrequency): number[] {
  switch (freq) {
    case '年3回（中間1回）':
      return [6]
    case '年4回（中間3回）':
      return [3, 6, 9]
    case '年12回（中間11回）':
      return [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    default:
      return []
  }
}

export function generateCorporationDeadlines(client: Client): DeadlineDraft[] {
  const profile = client.corporation
  if (!profile || !profile.fiscalYearEndMonth) return []
  const fye = getFiscalYearEndDate(profile)
  if (!fye) return []
  const [fyYear] = fye.split('-').map(Number)
  const periodLabel = `第${fyYear}期 (${fye.replace(/-/g, '/')}決算)`
  const drafts: DeadlineDraft[] = []

  // 法人税 / 地方法人税 / 住民税 / 事業税 / 特別法人事業税 確定申告
  const corpTaxDue = corporationFilingDueDate(fye)
  ;(['法人税', '地方法人税', '法人住民税', '法人事業税', '特別法人事業税'] as const).forEach(
    (category) => {
      drafts.push({
        clientId: client.id,
        category,
        kind: '確定申告',
        periodLabel,
        dueDate: corpTaxDue,
        status: '未着手',
        autoGenerated: true,
        note: '決算日から2ヶ月後 (申告期限延長特例を適用している場合は要調整)',
      })
    },
  )

  // 中間申告 (法人税・法人事業税関連)
  const corpInterimDue = corporationInterimFilingDueDate(fye)
  ;(['法人税', '地方法人税', '法人住民税', '法人事業税', '特別法人事業税'] as const).forEach(
    (category) => {
      drafts.push({
        clientId: client.id,
        category,
        kind: '中間申告',
        periodLabel: `${periodLabel} 中間`,
        dueDate: corpInterimDue,
        status: '未着手',
        autoGenerated: true,
        note: '事業年度開始から6ヶ月を経過した日から2ヶ月以内 (該当する場合のみ)',
      })
    },
  )

  // 消費税 (課税事業者のみ)
  if (profile.consumptionTaxMethod && profile.consumptionTaxMethod !== '免税事業者' && profile.consumptionTaxMethod !== '該当なし') {
    drafts.push({
      clientId: client.id,
      category: '消費税',
      kind: '確定申告',
      periodLabel,
      dueDate: corpTaxDue,
      status: '未着手',
      autoGenerated: true,
      note: '課税期間終了後2ヶ月以内',
    })

    // 消費税中間
    const interimMonths = consumptionInterimMonthsList(profile.consumptionTaxFrequency)
    if (interimMonths.length > 0) {
      const [fyEndY, fyEndM] = fye.split('-').map(Number)
      // 事業年度開始 = 決算月+1月
      const { year: startY, month: startM } = addMonths(fyEndY, fyEndM, -11)
      interimMonths.forEach((n, idx) => {
        // 中間対象期間の末日 = 事業年度開始から n ヶ月後 の末日
        const { year: endY, month: endM } = addMonths(startY, startM, n - 1)
        const endDay = lastDayOfMonth(endY, endM)
        // 申告期限 = その2ヶ月後
        const { year: dueY, month: dueM } = addMonths(endY, endM, 2)
        const dueDay = Math.min(endDay, lastDayOfMonth(dueY, dueM))
        drafts.push({
          clientId: client.id,
          category: '消費税',
          kind: '中間申告',
          periodLabel: `${periodLabel} 中間${interimMonths.length > 1 ? `${idx + 1}回目` : ''}`,
          dueDate: toISODate(dueY, dueM, dueDay),
          status: '未着手',
          autoGenerated: true,
          note: '消費税中間申告・納付期限',
        })
      })
    }
  }

  // 償却資産税 (1/31)
  drafts.push({
    clientId: client.id,
    category: '償却資産税',
    kind: 'その他',
    periodLabel: `${fyYear}年1月1日 賦課期日`,
    dueDate: toISODate(fyYear, 1, 31),
    status: '未着手',
    autoGenerated: true,
    note: '1月1日時点の償却資産申告 (市区町村)',
  })

  // 年末調整 (1/31 法定調書提出期限)
  drafts.push({
    clientId: client.id,
    category: '年末調整',
    kind: '年末調整',
    periodLabel: `令和${fyYear - 2018}年分`,
    dueDate: toISODate(fyYear, 1, 31),
    status: '未着手',
    autoGenerated: true,
    note: '源泉徴収票・給与支払報告書・法定調書合計表 (1/31)',
  })
  drafts.push({
    clientId: client.id,
    category: '法定調書',
    kind: '法定調書',
    periodLabel: `令和${fyYear - 2018}年分`,
    dueDate: toISODate(fyYear, 1, 31),
    status: '未着手',
    autoGenerated: true,
    note: '法定調書合計表・支払調書の提出期限 (1/31)',
  })

  return drafts
}

export function generateIndividualDeadlines(client: Client): DeadlineDraft[] {
  if (client.entityType !== 'individual') return []
  const now = new Date()
  const year = now.getMonth() >= 0 && now.getMonth() <= 2 ? now.getFullYear() : now.getFullYear() + 1
  const label = `令和${year - 2019}年分`
  const drafts: DeadlineDraft[] = [
    {
      clientId: client.id,
      category: '所得税',
      kind: '確定申告',
      periodLabel: label,
      dueDate: toISODate(year, 3, 15),
      status: '未着手',
      autoGenerated: true,
      note: '個人所得税確定申告 (3/15)',
    },
    {
      clientId: client.id,
      category: '消費税',
      kind: '確定申告',
      periodLabel: label,
      dueDate: toISODate(year, 3, 31),
      status: '未着手',
      autoGenerated: true,
      note: '個人消費税確定申告 (3/31)',
    },
    // 予定納税 (7/31, 11/30)
    {
      clientId: client.id,
      category: '所得税',
      kind: '予定納税',
      periodLabel: `${label} 第1期`,
      dueDate: toISODate(year, 7, 31),
      status: '未着手',
      autoGenerated: true,
      note: '所得税予定納税 第1期 (7/31)',
    },
    {
      clientId: client.id,
      category: '所得税',
      kind: '予定納税',
      periodLabel: `${label} 第2期`,
      dueDate: toISODate(year, 11, 30),
      status: '未着手',
      autoGenerated: true,
      note: '所得税予定納税 第2期 (11/30)',
    },
  ]
  return drafts
}

export function generateDeadlineDrafts(client: Client): DeadlineDraft[] {
  if (client.entityType === 'corporation') return generateCorporationDeadlines(client)
  return generateIndividualDeadlines(client)
}

/** 期限の緊急度を日数から導出 */
export function classifyUrgency(dueDate: string, today: Date = new Date()):
  | 'overdue'
  | 'critical'
  | 'warning'
  | 'upcoming'
  | 'far' {
  const todayIso = today.toISOString().slice(0, 10)
  if (dueDate < todayIso) return 'overdue'
  const diff = Math.ceil(
    (new Date(dueDate).getTime() - new Date(todayIso).getTime()) / (1000 * 60 * 60 * 24),
  )
  if (diff <= 7) return 'critical'
  if (diff <= 30) return 'warning'
  if (diff <= 90) return 'upcoming'
  return 'far'
}

export function daysUntil(dueDate: string, today: Date = new Date()): number {
  const todayIso = today.toISOString().slice(0, 10)
  return Math.ceil(
    (new Date(dueDate).getTime() - new Date(todayIso).getTime()) / (1000 * 60 * 60 * 24),
  )
}
