/**
 * グループウェアのドメイン型定義
 */

export type EntityType = 'corporation' | 'individual'

export type CorporationType =
  | '株式会社'
  | '有限会社'
  | '合同会社'
  | '合資会社'
  | '合名会社'
  | '一般社団法人'
  | '一般財団法人'
  | '公益社団法人'
  | '公益財団法人'
  | 'NPO法人'
  | '医療法人'
  | '社会福祉法人'
  | '学校法人'
  | '宗教法人'
  | '協同組合'
  | 'その他'

export type TaxCategory =
  | '法人税'
  | '地方法人税'
  | '法人住民税'
  | '法人事業税'
  | '特別法人事業税'
  | '消費税'
  | '所得税'
  | '源泉所得税'
  | '年末調整'
  | '法定調書'
  | '償却資産税'
  | '印紙税'
  | '国税その他'

export type ConsumptionTaxMethod = '一般課税' | '簡易課税' | '2割特例' | '免税事業者' | '該当なし'

export type ConsumptionTaxFilingFrequency =
  | '年1回'
  | '年3回（中間1回）'
  | '年4回（中間3回）'
  | '年12回（中間11回）'
  | '該当なし'

export type DeadlineStatus = '未着手' | '資料回収中' | '作成中' | '申告書完成' | '提出済' | '納付済'

export interface ContactPerson {
  id: string
  name: string
  role?: string
  email?: string
  phone?: string
  note?: string
}

export interface TaxOfficeInfo {
  /** 所轄税務署 */
  nationalTaxOffice?: string
  /** 所轄都道府県税事務所 */
  prefecturalTaxOffice?: string
  /** 所轄市区町村役所 */
  municipalTaxOffice?: string
}

export interface CorporationProfile {
  corporationNumber?: string
  corporationType?: CorporationType
  representativeName?: string
  representativeTitle?: string
  establishedDate?: string
  capital?: number
  /** 決算月 (1-12) */
  fiscalYearEndMonth?: number
  /** 決算日 (1-31)。省略時は月末。 */
  fiscalYearEndDay?: number
  /** 事業年度開始月 (1-12) */
  fiscalYearStartMonth?: number
  /** 業種 */
  industry?: string
  /** 青色申告承認 */
  blueReturn?: boolean
  /** 消費税課税方式 */
  consumptionTaxMethod?: ConsumptionTaxMethod
  /** 消費税申告区分 */
  consumptionTaxFrequency?: ConsumptionTaxFilingFrequency
  /** インボイス登録番号 (T + 13桁) */
  invoiceRegistrationNumber?: string
  /** eLTAX利用者ID */
  eltaxId?: string
  /** e-Tax利用者識別番号 */
  etaxId?: string
}

export interface IndividualProfile {
  birthDate?: string
  spouse?: boolean
  dependents?: number
  mainIncomeType?: string
  blueReturn?: boolean
  consumptionTaxMethod?: ConsumptionTaxMethod
  invoiceRegistrationNumber?: string
}

export interface Client {
  id: string
  /** 顧問先名 */
  name: string
  /** フリガナ */
  nameKana?: string
  /** 法人 / 個人 */
  entityType: EntityType
  /** 顧問契約開始日 */
  contractStartDate?: string
  /** 顧問契約終了日 (退職時) */
  contractEndDate?: string
  /** 月次顧問報酬 */
  monthlyFee?: number
  address?: string
  postalCode?: string
  phone?: string
  email?: string
  website?: string
  corporation?: CorporationProfile
  individual?: IndividualProfile
  taxOffice?: TaxOfficeInfo
  contacts?: ContactPerson[]
  /** 管理対象税目 */
  taxCategories?: TaxCategory[]
  /** 自由メモ */
  memo?: string
  createdAt: string
  updatedAt: string
}

export interface Deadline {
  id: string
  clientId: string
  category: TaxCategory
  /** 種別: 確定 / 中間 / 予定納税 / 年末調整 / 法定調書 等 */
  kind: '確定申告' | '中間申告' | '予定納税' | '源泉納付' | '年末調整' | '法定調書' | '償却資産' | 'その他'
  /** 対象期間ラベル (例: 令和7事業年度 / R7.1-6) */
  periodLabel?: string
  /** 申告・納付期限 (ISO日付) */
  dueDate: string
  status: DeadlineStatus
  /** 備考 */
  note?: string
  /** 申告書提出日 */
  submittedAt?: string
  /** 納付日 */
  paidAt?: string
  /** 税額 */
  taxAmount?: number
  /** 自動生成された期限か (決算月などから派生) */
  autoGenerated?: boolean
  createdAt: string
  updatedAt: string
}

export type RequestItemStatus = '未依頼' | '依頼済' | '一部受領' | '受領済' | '不要'

export interface RequestItem {
  id: string
  clientId: string
  /** 紐づく申告期限 */
  deadlineId?: string
  title: string
  description?: string
  status: RequestItemStatus
  /** 回収希望日 */
  dueDate?: string
  requestedAt?: string
  receivedAt?: string
  assignee?: string
  createdAt: string
  updatedAt: string
}

export type LauncherAppType = 'web' | 'file' | 'note'

export interface LauncherApp {
  id: string
  name: string
  description?: string
  /** 起動URL (web) またはローカルパス (file) */
  url: string
  type: LauncherAppType
  /** 絵文字アイコン */
  icon?: string
  /** 色 */
  color?: string
  /** 新規タブで開く */
  openInNewTab?: boolean
  order: number
  createdAt: string
  updatedAt: string
}

export interface GroupwareData {
  clients: Client[]
  deadlines: Deadline[]
  requests: RequestItem[]
  launcherApps: LauncherApp[]
}
