'use client'

import { useRouter } from 'next/navigation'
import { useState, useTransition } from 'react'
import type {
  Client,
  ConsumptionTaxFilingFrequency,
  ConsumptionTaxMethod,
  CorporationType,
  EntityType,
  TaxCategory,
} from '@/lib/groupware/types'

const CORPORATION_TYPES: CorporationType[] = [
  '株式会社',
  '有限会社',
  '合同会社',
  '合資会社',
  '合名会社',
  '一般社団法人',
  '一般財団法人',
  '公益社団法人',
  '公益財団法人',
  'NPO法人',
  '医療法人',
  '社会福祉法人',
  '学校法人',
  '宗教法人',
  '協同組合',
  'その他',
]

const CONSUMPTION_METHODS: ConsumptionTaxMethod[] = [
  '一般課税',
  '簡易課税',
  '2割特例',
  '免税事業者',
  '該当なし',
]

const CONSUMPTION_FREQUENCIES: ConsumptionTaxFilingFrequency[] = [
  '年1回',
  '年3回（中間1回）',
  '年4回（中間3回）',
  '年12回（中間11回）',
  '該当なし',
]

const TAX_CATEGORIES: TaxCategory[] = [
  '法人税',
  '地方法人税',
  '法人住民税',
  '法人事業税',
  '特別法人事業税',
  '消費税',
  '所得税',
  '源泉所得税',
  '年末調整',
  '法定調書',
  '償却資産税',
  '印紙税',
  '国税その他',
]

export function ClientForm({ initial, mode }: { initial?: Client; mode: 'create' | 'edit' }) {
  const router = useRouter()
  const [pending, startTransition] = useTransition()
  const [error, setError] = useState<string | null>(null)

  const [name, setName] = useState(initial?.name ?? '')
  const [nameKana, setNameKana] = useState(initial?.nameKana ?? '')
  const [entityType, setEntityType] = useState<EntityType>(initial?.entityType ?? 'corporation')
  const [contractStartDate, setContractStartDate] = useState(initial?.contractStartDate ?? '')
  const [monthlyFee, setMonthlyFee] = useState<string>(
    initial?.monthlyFee !== undefined ? String(initial.monthlyFee) : '',
  )
  const [postalCode, setPostalCode] = useState(initial?.postalCode ?? '')
  const [address, setAddress] = useState(initial?.address ?? '')
  const [phone, setPhone] = useState(initial?.phone ?? '')
  const [email, setEmail] = useState(initial?.email ?? '')
  const [website, setWebsite] = useState(initial?.website ?? '')
  const [memo, setMemo] = useState(initial?.memo ?? '')

  const [corporationType, setCorporationType] = useState<CorporationType | ''>(
    initial?.corporation?.corporationType ?? '',
  )
  const [corporationNumber, setCorporationNumber] = useState(
    initial?.corporation?.corporationNumber ?? '',
  )
  const [representativeName, setRepresentativeName] = useState(
    initial?.corporation?.representativeName ?? '',
  )
  const [representativeTitle, setRepresentativeTitle] = useState(
    initial?.corporation?.representativeTitle ?? '代表取締役',
  )
  const [establishedDate, setEstablishedDate] = useState(
    initial?.corporation?.establishedDate ?? '',
  )
  const [capital, setCapital] = useState<string>(
    initial?.corporation?.capital !== undefined ? String(initial.corporation.capital) : '',
  )
  const [fiscalYearEndMonth, setFiscalYearEndMonth] = useState<string>(
    initial?.corporation?.fiscalYearEndMonth !== undefined
      ? String(initial.corporation.fiscalYearEndMonth)
      : '',
  )
  const [fiscalYearEndDay, setFiscalYearEndDay] = useState<string>(
    initial?.corporation?.fiscalYearEndDay !== undefined
      ? String(initial.corporation.fiscalYearEndDay)
      : '',
  )
  const [industry, setIndustry] = useState(initial?.corporation?.industry ?? '')
  const [blueReturn, setBlueReturn] = useState<boolean>(
    initial?.corporation?.blueReturn ?? initial?.individual?.blueReturn ?? true,
  )
  const [consumptionTaxMethod, setConsumptionTaxMethod] = useState<ConsumptionTaxMethod | ''>(
    (initial?.corporation?.consumptionTaxMethod ?? initial?.individual?.consumptionTaxMethod ?? '') as
      | ConsumptionTaxMethod
      | '',
  )
  const [consumptionTaxFrequency, setConsumptionTaxFrequency] =
    useState<ConsumptionTaxFilingFrequency | ''>(
      (initial?.corporation?.consumptionTaxFrequency ?? '') as ConsumptionTaxFilingFrequency | '',
    )
  const [invoiceRegistrationNumber, setInvoiceRegistrationNumber] = useState(
    initial?.corporation?.invoiceRegistrationNumber ??
      initial?.individual?.invoiceRegistrationNumber ??
      '',
  )
  const [eltaxId, setEltaxId] = useState(initial?.corporation?.eltaxId ?? '')
  const [etaxId, setEtaxId] = useState(initial?.corporation?.etaxId ?? '')

  const [nationalTaxOffice, setNationalTaxOffice] = useState(initial?.taxOffice?.nationalTaxOffice ?? '')
  const [prefecturalTaxOffice, setPrefecturalTaxOffice] = useState(
    initial?.taxOffice?.prefecturalTaxOffice ?? '',
  )
  const [municipalTaxOffice, setMunicipalTaxOffice] = useState(initial?.taxOffice?.municipalTaxOffice ?? '')

  const [taxCategories, setTaxCategories] = useState<TaxCategory[]>(
    initial?.taxCategories ?? [
      '法人税',
      '地方法人税',
      '法人住民税',
      '法人事業税',
      '特別法人事業税',
      '消費税',
      '源泉所得税',
      '年末調整',
      '法定調書',
      '償却資産税',
    ],
  )

  const [autoGenerateDeadlines, setAutoGenerateDeadlines] = useState(true)

  function toggleCategory(cat: TaxCategory) {
    setTaxCategories((prev) =>
      prev.includes(cat) ? prev.filter((c) => c !== cat) : [...prev, cat],
    )
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setError(null)
    if (!name.trim()) {
      setError('顧問先名を入力してください')
      return
    }

    const payload: Partial<Client> & { autoGenerateDeadlines?: boolean } = {
      name: name.trim(),
      nameKana: nameKana.trim() || undefined,
      entityType,
      contractStartDate: contractStartDate || undefined,
      monthlyFee: monthlyFee ? Number(monthlyFee) : undefined,
      postalCode: postalCode.trim() || undefined,
      address: address.trim() || undefined,
      phone: phone.trim() || undefined,
      email: email.trim() || undefined,
      website: website.trim() || undefined,
      memo: memo.trim() || undefined,
      taxCategories,
      taxOffice: {
        nationalTaxOffice: nationalTaxOffice.trim() || undefined,
        prefecturalTaxOffice: prefecturalTaxOffice.trim() || undefined,
        municipalTaxOffice: municipalTaxOffice.trim() || undefined,
      },
    }

    if (entityType === 'corporation') {
      payload.corporation = {
        corporationType: (corporationType || undefined) as CorporationType | undefined,
        corporationNumber: corporationNumber.trim() || undefined,
        representativeName: representativeName.trim() || undefined,
        representativeTitle: representativeTitle.trim() || undefined,
        establishedDate: establishedDate || undefined,
        capital: capital ? Number(capital) : undefined,
        fiscalYearEndMonth: fiscalYearEndMonth ? Number(fiscalYearEndMonth) : undefined,
        fiscalYearEndDay: fiscalYearEndDay ? Number(fiscalYearEndDay) : undefined,
        industry: industry.trim() || undefined,
        blueReturn,
        consumptionTaxMethod: (consumptionTaxMethod || undefined) as ConsumptionTaxMethod | undefined,
        consumptionTaxFrequency: (consumptionTaxFrequency || undefined) as
          | ConsumptionTaxFilingFrequency
          | undefined,
        invoiceRegistrationNumber: invoiceRegistrationNumber.trim() || undefined,
        eltaxId: eltaxId.trim() || undefined,
        etaxId: etaxId.trim() || undefined,
      }
    } else {
      payload.individual = {
        blueReturn,
        consumptionTaxMethod: (consumptionTaxMethod || undefined) as ConsumptionTaxMethod | undefined,
        invoiceRegistrationNumber: invoiceRegistrationNumber.trim() || undefined,
      }
    }
    payload.autoGenerateDeadlines = autoGenerateDeadlines

    startTransition(async () => {
      try {
        const res = await fetch(
          mode === 'create' ? '/api/groupware/clients' : `/api/groupware/clients/${initial!.id}`,
          {
            method: mode === 'create' ? 'POST' : 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(
              mode === 'create'
                ? payload
                : { ...payload, regenerateDeadlines: autoGenerateDeadlines },
            ),
          },
        )
        if (!res.ok) {
          const err = await res.json().catch(() => ({}))
          throw new Error(err.error ?? '保存に失敗しました')
        }
        const json = await res.json()
        const id = json.client?.id ?? initial?.id
        router.push(`/clients/${id}`)
        router.refresh()
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e))
      }
    })
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-8">
      {error ? (
        <div className="gw-card p-4 border-[#ff3b30]/30 text-[#ff3b30]">{error}</div>
      ) : null}

      <Section title="基本情報">
        <Field label="顧問先名 *">
          <input className="gw-input" value={name} onChange={(e) => setName(e.target.value)} required />
        </Field>
        <Field label="フリガナ">
          <input className="gw-input" value={nameKana} onChange={(e) => setNameKana(e.target.value)} />
        </Field>
        <Field label="区分 *">
          <select
            className="gw-select"
            value={entityType}
            onChange={(e) => setEntityType(e.target.value as EntityType)}
          >
            <option value="corporation">法人</option>
            <option value="individual">個人</option>
          </select>
        </Field>
        <Field label="契約開始日">
          <input
            type="date"
            className="gw-input"
            value={contractStartDate}
            onChange={(e) => setContractStartDate(e.target.value)}
          />
        </Field>
        <Field label="月額顧問料 (円)">
          <input
            type="number"
            className="gw-input"
            value={monthlyFee}
            onChange={(e) => setMonthlyFee(e.target.value)}
          />
        </Field>
      </Section>

      <Section title="連絡先">
        <Field label="郵便番号">
          <input className="gw-input" value={postalCode} onChange={(e) => setPostalCode(e.target.value)} />
        </Field>
        <Field label="住所" wide>
          <input className="gw-input" value={address} onChange={(e) => setAddress(e.target.value)} />
        </Field>
        <Field label="電話">
          <input className="gw-input" value={phone} onChange={(e) => setPhone(e.target.value)} />
        </Field>
        <Field label="メール">
          <input className="gw-input" value={email} onChange={(e) => setEmail(e.target.value)} />
        </Field>
        <Field label="Web">
          <input className="gw-input" value={website} onChange={(e) => setWebsite(e.target.value)} />
        </Field>
      </Section>

      {entityType === 'corporation' ? (
        <Section title="法人情報">
          <Field label="法人種別">
            <select
              className="gw-select"
              value={corporationType}
              onChange={(e) => setCorporationType(e.target.value as CorporationType)}
            >
              <option value="">選択</option>
              {CORPORATION_TYPES.map((t) => (
                <option key={t} value={t}>
                  {t}
                </option>
              ))}
            </select>
          </Field>
          <Field label="法人番号 (13桁)">
            <input
              className="gw-input"
              value={corporationNumber}
              onChange={(e) => setCorporationNumber(e.target.value)}
            />
          </Field>
          <Field label="代表者氏名">
            <input
              className="gw-input"
              value={representativeName}
              onChange={(e) => setRepresentativeName(e.target.value)}
            />
          </Field>
          <Field label="代表者役職">
            <input
              className="gw-input"
              value={representativeTitle}
              onChange={(e) => setRepresentativeTitle(e.target.value)}
            />
          </Field>
          <Field label="設立日">
            <input
              type="date"
              className="gw-input"
              value={establishedDate}
              onChange={(e) => setEstablishedDate(e.target.value)}
            />
          </Field>
          <Field label="資本金 (円)">
            <input
              type="number"
              className="gw-input"
              value={capital}
              onChange={(e) => setCapital(e.target.value)}
            />
          </Field>
          <Field label="決算月 *">
            <select
              className="gw-select"
              value={fiscalYearEndMonth}
              onChange={(e) => setFiscalYearEndMonth(e.target.value)}
            >
              <option value="">選択</option>
              {Array.from({ length: 12 }).map((_, i) => (
                <option key={i + 1} value={i + 1}>
                  {i + 1}月
                </option>
              ))}
            </select>
          </Field>
          <Field label="決算日 (空欄 = 月末)">
            <input
              type="number"
              min={1}
              max={31}
              className="gw-input"
              value={fiscalYearEndDay}
              onChange={(e) => setFiscalYearEndDay(e.target.value)}
            />
          </Field>
          <Field label="業種">
            <input className="gw-input" value={industry} onChange={(e) => setIndustry(e.target.value)} />
          </Field>
          <Field label="e-Tax 利用者識別番号">
            <input className="gw-input" value={etaxId} onChange={(e) => setEtaxId(e.target.value)} />
          </Field>
          <Field label="eLTAX 利用者ID">
            <input className="gw-input" value={eltaxId} onChange={(e) => setEltaxId(e.target.value)} />
          </Field>
        </Section>
      ) : null}

      <Section title="税務・インボイス">
        <Field label="青色申告承認">
          <label className="inline-flex items-center gap-2 mt-2">
            <input
              type="checkbox"
              checked={blueReturn}
              onChange={(e) => setBlueReturn(e.target.checked)}
            />
            <span className="text-[14px] text-ink-soft">承認あり</span>
          </label>
        </Field>
        <Field label="消費税課税方式">
          <select
            className="gw-select"
            value={consumptionTaxMethod}
            onChange={(e) => setConsumptionTaxMethod(e.target.value as ConsumptionTaxMethod)}
          >
            <option value="">選択</option>
            {CONSUMPTION_METHODS.map((m) => (
              <option key={m} value={m}>
                {m}
              </option>
            ))}
          </select>
        </Field>
        {entityType === 'corporation' ? (
          <Field label="消費税申告区分">
            <select
              className="gw-select"
              value={consumptionTaxFrequency}
              onChange={(e) =>
                setConsumptionTaxFrequency(e.target.value as ConsumptionTaxFilingFrequency)
              }
            >
              <option value="">選択</option>
              {CONSUMPTION_FREQUENCIES.map((f) => (
                <option key={f} value={f}>
                  {f}
                </option>
              ))}
            </select>
          </Field>
        ) : null}
        <Field label="インボイス登録番号 (T + 13桁)">
          <input
            className="gw-input"
            value={invoiceRegistrationNumber}
            onChange={(e) => setInvoiceRegistrationNumber(e.target.value)}
            placeholder="T1234567890123"
          />
        </Field>
      </Section>

      <Section title="所轄官署">
        <Field label="所轄税務署">
          <input
            className="gw-input"
            value={nationalTaxOffice}
            onChange={(e) => setNationalTaxOffice(e.target.value)}
          />
        </Field>
        <Field label="所轄都道府県税事務所">
          <input
            className="gw-input"
            value={prefecturalTaxOffice}
            onChange={(e) => setPrefecturalTaxOffice(e.target.value)}
          />
        </Field>
        <Field label="所轄市区町村役所">
          <input
            className="gw-input"
            value={municipalTaxOffice}
            onChange={(e) => setMunicipalTaxOffice(e.target.value)}
          />
        </Field>
      </Section>

      <Section title="管理対象税目">
        <div className="col-span-2 flex flex-wrap gap-2">
          {TAX_CATEGORIES.map((cat) => {
            const active = taxCategories.includes(cat)
            return (
              <button
                type="button"
                key={cat}
                onClick={() => toggleCategory(cat)}
                className={
                  'px-3 py-1.5 rounded-full text-[13px] border transition-colors ' +
                  (active
                    ? 'bg-ink text-white border-ink'
                    : 'bg-white text-ink-soft border-black/10 hover:border-black/30')
                }
              >
                {cat}
              </button>
            )
          })}
        </div>
      </Section>

      <Section title="メモ">
        <div className="col-span-2">
          <textarea
            className="gw-input min-h-[110px] resize-y"
            value={memo}
            onChange={(e) => setMemo(e.target.value)}
            placeholder="連絡事項、特記事項など"
          />
        </div>
      </Section>

      <div className="gw-card p-5 flex items-center justify-between">
        <label className="flex items-center gap-2 text-[14px]">
          <input
            type="checkbox"
            checked={autoGenerateDeadlines}
            onChange={(e) => setAutoGenerateDeadlines(e.target.checked)}
          />
          <span>{mode === 'create' ? '登録時に申告期限を自動生成する' : '保存時に申告期限の下書きを追加生成する'}</span>
        </label>
        <div className="flex gap-3">
          <button
            type="button"
            onClick={() => router.back()}
            className="gw-btn-secondary"
            disabled={pending}
          >
            キャンセル
          </button>
          <button type="submit" className="gw-btn-primary" disabled={pending}>
            {pending ? '保存中…' : mode === 'create' ? '顧問先を登録' : '変更を保存'}
          </button>
        </div>
      </div>
    </form>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="gw-card p-6">
      <h3 className="text-[18px] font-semibold tracking-tight mb-5">{title}</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{children}</div>
    </div>
  )
}

function Field({
  label,
  children,
  wide,
}: {
  label: string
  children: React.ReactNode
  wide?: boolean
}) {
  return (
    <label className={'block ' + (wide ? 'md:col-span-2' : '')}>
      <div className="text-[12px] font-medium text-ink-soft mb-1.5">{label}</div>
      {children}
    </label>
  )
}
