import { NextResponse } from 'next/server'
import { bulkCreateDeadlines, createClient, listClients } from '@/lib/groupware/store'
import { generateDeadlineDrafts } from '@/lib/groupware/deadlines'
import type { Client } from '@/lib/groupware/types'

export const runtime = 'nodejs'

export async function GET() {
  const clients = await listClients()
  return NextResponse.json({ clients })
}

export async function POST(req: Request) {
  const body = (await req.json()) as Partial<Client> & { autoGenerateDeadlines?: boolean }
  if (!body.name || !body.entityType) {
    return NextResponse.json({ error: 'name and entityType are required' }, { status: 400 })
  }
  const client = await createClient({
    name: body.name,
    nameKana: body.nameKana,
    entityType: body.entityType,
    contractStartDate: body.contractStartDate,
    contractEndDate: body.contractEndDate,
    monthlyFee: body.monthlyFee,
    address: body.address,
    postalCode: body.postalCode,
    phone: body.phone,
    email: body.email,
    website: body.website,
    corporation: body.corporation,
    individual: body.individual,
    taxOffice: body.taxOffice,
    contacts: body.contacts ?? [],
    taxCategories: body.taxCategories ?? [],
    memo: body.memo,
  })

  let deadlinesCreated = 0
  if (body.autoGenerateDeadlines !== false) {
    const drafts = generateDeadlineDrafts(client)
    if (drafts.length > 0) {
      const created = await bulkCreateDeadlines(drafts)
      deadlinesCreated = created.length
    }
  }

  return NextResponse.json({ client, deadlinesCreated }, { status: 201 })
}
